### ISSUE TITLE
Proposition to improve the naming for CSVExtractor

### ISSUE THREAD

**Issue by tomaszhanc** [flow-php/etl-adapter-csv#103]
This extractor: https://github.com/flow-php/etl-adapter-csv/blob/1.x/src/Flow/ETL/Adapter/CSV/League/CSVExtractor.php can work only with local files. `League\Csv\Reader` class when iterates over the lines uses `seek` operation, which is not supported by external paths, like URL to a file on Amazon Storage or Azure Storage. 

I was thinking if we can rename that extractor to give a hint to developers that **it works only with local files**. It won't prevent from such mistakes, but at least will give a hint. We could name it eg: `LocalFileCSVExtractor`. Another option would be to not use `path` as a string but a VO called `LocalFile` or `LocalFilePath`. Renaming the extractor is easier and the outcome is pretty the same. 

Both options introduce a BC break, so I'll need to create a new extractor and call it `LocalFileCSVExtractor` and mark the current as deprecated.

Let me know what do you think about.

**Comment by norberttech** [comment]
Yeah, I can see how this can be missed, but also, I'm not sure if the change is worth the effort since it's no solving the problem, it's just pushing it to the end user. 
What we could think about is maybe another, UrlFileExtractor that would take any url, download it to some tmp location and then take any of the existing extractors and read from the file.
It could take some extra arguments like HTTP haders or something that would make downloading even secured files possible. After extracting given temp file it could remove it or keep (based on some arguments) 
And then we could maybe try to detect in this extractor (or any else that has issues with URLs) that given path is url which is not supported and suggest in exception message to use that other extractor. 

Btw. League CSV reader is not supporting reading directly from URLs at all?
